apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-deployment-blue # For Blue environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coinbase
      version: blue
  template:
    metadata:
      labels:
        app: coinbase
        version: blue
    spec:
      containers:
        - name: coinbase
          image: coinbase-image-tag  # Placeholder, replaced in GitHub Actions
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-deployment-green # For Green environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coinbase
      version: green
  template:
    metadata:
      labels:
        app: coinbase
        version: green
    spec:
      containers:
        - name: coinbase
          image: damianpeiris/github-actions-demo  # Static green image
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
